### ISSUE TITLE
I get stuck when I open file with tramp and then start a eshell  session

### ISSUE THREAD

**Issue by samrayleung** [kaihaosw/eshell-prompt-extras#17]
This is my configuration about eshell-prompt-extras:
```
(use-package eshell-prompt-extras
  :ensure t
  :config (progn
	    (with-eval-after-load "esh-opt"
	      (use-package virtualenvwrapper :ensure t)
	      (venv-initialize-eshell)
	      (autoload 'epe-theme-lambda "eshell-prompt-extras")
	      (setq eshell-highlight-prompt nil
		    eshell-prompt-function 'epe-theme-lambda))
	    ))
```
When I open a file with tramp, and then start a eshell session, type some commands, It takes 5 seconds to response to, but I just open a file in my virtual machine. It is so weird, and when I 
comment the configuration about eshell-prompt-extras, everything works fine. Could you help me out ?

**Comment by kaihaosw** [comment]
I don't have any clue about why this happen. Eshell is slower than your "real" shell, but should not slow like this. Can you give me more information about that?
