### ISSUE TITLE
eshell-prompt-extras broken w/ TRAMP in Emacs 26

### ISSUE THREAD

**Issue by eklitzke** [kaihaosw/eshell-prompt-extras#18]
The function `tramp-file-name-real-host` has been removed upstream: https://github.com/emacs-mirror/emacs/commit/dca22e86e02d16a31128c163925b13404f777c0f . You are now supposed to use the `tramp-file-name` defstruct.

**Comment by kaihaosw** [comment]
I'm currently use the stable version: GNU Emacs 25.2.1, and Emacs25 don't have `tramp-file-name`.
Will you pull a request?

**Comment by xuchunyang** [comment]
It should be fixed now. I'm running latest Emacs 26 and have tested it.
