### ISSUE TITLE
Make a stable release to be included in MELPA stable

### ISSUE THREAD

**Issue by matthewbauer** [kaihaosw/eshell-prompt-extras#19]
Hi,

I've been using eshell-prompt-extras regularly now and it seems stable. Can you make a versioned release so that it can be included in the MELPA stable set?

**Comment by kaihaosw** [comment]
I feel very sorry for not seeing this because my personal reason.
I will try to make it in MELPA stable, and I will let you know.
Thanks.

**Comment by xuchunyang** [comment]
I've just pushed a tag. This package should be available from Melpa-stable in a few hours.
