### ISSUE TITLE
TRAMP + git is very slow

### ISSUE THREAD

**Issue by olessavluk** [kaihaosw/eshell-prompt-extras#20]
Hi,
`eshell` is extremely slow when I'm using it over TRAMP in the folder with `git`.

Seems like this is caused by `(eshell-search-path "git")` [here ](https://github.com/kaihaosw/eshell-prompt-extras/blob/master/eshell-prompt-extras.el#L257)
Because when I run `M-x benchmark`: `(eshell-search-path "git")`:
 - inside a project with git: `Elapsed time: 3.389904s`
 - inside `/home` folder: `Elapsed time: 0.421523s`

But on my local machine it works immediately

**Comment by xuchunyang** [comment]
It isn't that slow from here:

```
Welcome to the Emacs shell

@elpa /ssh:elpa:/home/xcy λ cd eshell-prompt-extras/
@elpa /s/h/xcy/eshell-prompt-extras λ (message "%s" default-directory)
/ssh:elpa:/home/xcy/eshell-prompt-extras/
@elpa /s/h/xcy/eshell-prompt-extras λ (benchmark-run (eshell-search-path "git"))
(0.129631 0 0.0)
@elpa /s/h/xcy/eshell-prompt-extras λ 
```

however, as you can see,  the git branch is not showing, thus the git feature is not working here.

So considering it's slow (I'm not sure the cause/how to fix) and also useless (I think this can be fixed), I'm going to disable the git feature for remote git repo for now.

**Comment by olessavluk** [comment]
Thanks!
